name = "workouts-production"
main = "worker.js"
compatibility_date = "2025-11-23"

kv_namespaces = [{
                    "binding": "WORKOUTS",
                    "id": "87410bddd9f346f393f03545c79cf00c"
                 }]

[env.production]
name = "workouts-production"
# Ensure production deployments keep the WORKOUTS KV binding intact.
kv_namespaces = [{
                    "binding": "WORKOUTS",
                    "id": "87410bddd9f346f393f03545c79cf00c"
                 }]
