name = "gumroad-products-production"         # service name youâ€™ll see in the CF dashboard
main = "worker.js"                # entry file relative to this folder
compatibility_date = "2025-11-12" # use today's date

[env.production]
# put prod-only settings here later if you need
name = "gumroad-products-production"
